### ISSUE TITLE
部分功能的配置文件推荐写法

### ISSUE THREAD

**Issue by happy888888** [happy888888/BiliExp#178]
基本上只有使用***风纪投票***，***直播心跳(小心心)***和***天选时刻抽奖***以及***动态转发抽奖***功能需要修改配置文件，使用其他功能的用户***只用配置好cookie***后使用[默认配置](https://github.com/happy888888/BiliExp/blob/master/config/config.json)就好，这里列出这些功能的推荐配置

#### (1)Actions环境
配置文件/config/config.json(对应secrets advconfig)
```
{
    "version": "1.2.0",
    "default": {
        "judgement_task": {
            "enable": true,
            "run_once": true,
            "params": {
                "vote": 4,
                "attr": 0
            },
            "vote_num": 20,
            "check_interval": 420,
            "timeout": 850
        }
    },
    "log_file": "BiliExp.log",
    "log_console": true,
    "users": [{
        "cookieDatas": {
            "SESSDATA": "你的cookie",
            "bili_jct": "你的cookie",
            "DedeUserID": "你的uid"
        },
        "tasks": {}
    }]
}
```
workflow配置(对应.github/workflows/run_BiliExp.yml文件)
```
name: 'run BiliExp'

on:
  schedule:
    - cron: '*/30 21-23,5-7,13-15 * * *'
  watch:
    types: started
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        ref: BiliExp-Actions

    - name: 安装依赖库
      run: |
          sudo -H pip3 install --upgrade setuptools
          sudo -H pip3 install -r requirements.txt
    - name: 配置用户信息
      run: python3 secrets2config.py
      env:
          ADVCONFIG: ${{ secrets.ADVCONFIG }}
          BILICONFIG: ${{ secrets.BILICONFIG }}
          PUSH_MESSAGE: ${{ secrets.PUSH_MESSAGE }}

    - name: 执行BiliExp.py
      run: python3 BiliExp.py
```
#### (2)腾讯云函数环境
配置文件/config/config.json(云函数上也是这个路径)，***同上面Actions的配置***
触发器使用自定义cron `0 */30 5-7,13-15,21-23 * * * *`
![image](https://user-images.githubusercontent.com/67217225/105199305-9a21aa00-5b79-11eb-9a66-debaf0de7cc3.png)

#### (1)Actions环境
配置文件/config/config.json(对应secrets advconfig)
```
{
    "version": "1.2.0",
    "default": {
        "xlive_anchor_task": {
            "enable": true, 
            "anchor_type": [[0, 0], [1, 0]],
            "delay": 0,
            "gift_filter": ["照片","自拍","代金卷","船长","优惠券","上船","素颜照","加速器","自画像","抵扣卷","写真","王者","舰长"],
            "room_filter": [],
            "danmu_filter": [],
            "price_limit": 0,
            "unfollow": true,
            "follow_group": "天选时刻",
            "clean_group_interval": 0,
            "search_interval": 500,
            "search_areas": [
                {"paid": 1,"aid": 0,"sort": "","ps": 50},
                {"paid": 2,"aid": 0,"sort": "","ps": 50},
                {"paid": 3,"aid": 0,"sort": "","ps": 50},
                {"paid": 6,"aid": 0,"sort": "","ps": 50}
            ],
            "timeout": 3300,
            "run_once": false
    },
    "log_file": "BiliExp.log",
    "log_console": true,
    "users": [{
        "cookieDatas": {
            "SESSDATA": "你的cookie",
            "bili_jct": "你的cookie",
            "DedeUserID": "你的uid"
        },
        "tasks": {}
    }]
}
```
workflow配置(对应.github/workflows/run_BiliExp.yml文件)
```
name: 'run BiliExp'

on:
  schedule:
    - cron: '*/10 0-17 * * *'
  watch:
    types: started
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        ref: BiliExp-Actions

    - name: 安装依赖库
      run: |
          sudo -H pip3 install --upgrade setuptools
          sudo -H pip3 install -r requirements.txt
    - name: 配置用户信息
      run: python3 secrets2config.py
      env:
          ADVCONFIG: ${{ secrets.ADVCONFIG }}
          BILICONFIG: ${{ secrets.BILICONFIG }}
          PUSH_MESSAGE: ${{ secrets.PUSH_MESSAGE }}

    - name: 执行BiliExp.py
      run: python3 BiliExp.py
```
#### (2)腾讯云函数环境
配置文件/config/config.json(云函数上也是这个路径)
```
{
    "version": "1.2.0",
    "default": {
        "xlive_anchor_task": {
            "enable": true, 
            "anchor_type": [[0, 0], [1, 0]],
            "delay": 0,
            "gift_filter": ["照片","自拍","代金卷","船长","优惠券","上船","素颜照","加速器","自画像","抵扣卷","写真","王者","舰长"],
            "room_filter": [],
            "danmu_filter": [],
            "price_limit": 0,
            "unfollow": true,
            "follow_group": "天选时刻",
            "clean_group_interval": 0,
            "search_interval": 500,
            "search_areas": [
                {"paid": 1,"aid": 0,"sort": "","ps": 50},
                {"paid": 2,"aid": 0,"sort": "","ps": 50},
                {"paid": 3,"aid": 0,"sort": "","ps": 50},
                {"paid": 6,"aid": 0,"sort": "","ps": 50}
            ],
            "timeout": 850,
            "run_once": true
    },
    "log_file": "BiliExp.log",
    "log_console": true,
    "users": [{
        "cookieDatas": {
            "SESSDATA": "你的cookie",
            "bili_jct": "你的cookie",
            "DedeUserID": "你的uid"
        },
        "tasks": {}
    }]
}
```
触发器使用自定义cron `0 */10 8-23,0-1 * * * *`
![image](https://user-images.githubusercontent.com/67217225/105201427-d5bd7380-5b7b-11eb-97f8-3f5aa58a31f4.png)

### 3. 使用直播心跳任务(获取小心心)
***每获取一个小心心需要在一个有粉丝牌的房间心跳5分钟，每天最多获取24个，如果你只有一个粉丝牌就需要心跳2小时，如果你有两个粉丝牌就需要心跳1小时，如果你有24个粉丝牌就需要心跳5分钟*** 这里以有3个粉丝牌需要心跳40分钟为例
#### (1)Actions环境
配置文件/config/config.json(对应secrets advconfig)
```
{
    "version": "1.2.0",
    "xlive_heartbeat_task": {
            "enable": true,
            "medal_room": true,
            "room_id": [],
            "send_msg": "打卡",  //给每个有粉丝牌的直播间发送一条"打卡"消息可点亮灰色的粉丝牌和加100亲密度
            "timeout": 42, //心跳分钟数，留2分钟余裕
    },
    "log_file": "BiliExp.log",
    "log_console": true,
    "users": [{
        "cookieDatas": {
            "SESSDATA": "你的cookie",
            "bili_jct": "你的cookie",
            "DedeUserID": "你的uid"
        },
        "tasks": {}
    }]
}
```
workflow配置不需要变动

#### (2)腾讯云函数环境
配置文件/config/config.json(云函数上也是这个路径)
```
{
    "version": "1.2.0",
    "xlive_heartbeat_task": {
            "enable": true,
            "medal_room": true,
            "room_id": [],
            "send_msg": "",
            "timeout": 11, //云函数每次最多执行15分钟，这里每次运行10分钟每个房间得两次小心心
    },
    "log_file": "BiliExp.log",
    "log_console": true,
    "users": [{
        "cookieDatas": {
            "SESSDATA": "你的cookie",
            "bili_jct": "你的cookie",
            "DedeUserID": "你的uid"
        },
        "tasks": {}
    }]
}
```
触发器使用自定义cron `0 */30 12-13 * * * *`  由于每次只获取了10分钟的小心心，在假设有3个粉丝牌的情况下需要执行4次，这里在12点和13点的整点和半点分别执行1次
![image](https://user-images.githubusercontent.com/67217225/105203984-aeb47100-5b7e-11eb-96cd-ecfddd0e539e.png)

### 4. 使用动态转发抽奖任务
***注意本功能不会自动关注抽奖up主，需要你自行关注否则无效***
#### (1)Actions环境
配置文件/config/config.json(对应secrets advconfig)
```
{
    "version": "1.2.0",
    "default": {
        "lottery_task": {
            "enable": true,
            "reply": ["从未中奖，从未放弃[doge]", "支持支持"],
            "repost": ["从未中奖，从未放弃[doge]", "支持支持"],
            "keywords": ["^((?!恭喜).)*#互动抽奖#((?!恭喜).)*$", "^((?!恭喜).)*#抽奖#((?!恭喜).)*$", ".*(转|抽|评).*(转|抽|评).*(转|抽|评).*"],
            "repost_with_tag": {
                "fix": 1,
                "except": ["抽奖"],
                "reply_with_tag": false
            },
            "time_quantum": [-43200, 43200],
            "delay": [15, 25],
    },
    "log_file": "BiliExp.log",
    "log_console": true,
    "users": [{
        "cookieDatas": {
            "SESSDATA": "你的cookie",
            "bili_jct": "你的cookie",
            "DedeUserID": "你的uid"
        },
        "tasks": {}
    }]
}
```
workflow配置不需要变动
#### (2)腾讯云函数环境
配置文件/config/config.json(云函数上也是这个路径)
```
{
    "version": "1.2.0",
    "default": {
        "lottery_task": {
            "enable": true,
            "reply": ["从未中奖，从未放弃[doge]", "支持支持"],
            "repost": ["从未中奖，从未放弃[doge]", "支持支持"],
            "keywords": ["^((?!恭喜).)*#互动抽奖#((?!恭喜).)*$", "^((?!恭喜).)*#抽奖#((?!恭喜).)*$", ".*(转|抽|评).*(转|抽|评).*(转|抽|评).*"],
            "repost_with_tag": {
                "fix": 1,
                "except": ["抽奖"],
                "reply_with_tag": false
            },
            "time_quantum": [0, 600],
            "delay": [6, 8],
    },
    "log_file": "BiliExp.log",
    "log_console": true,
    "users": [{
        "cookieDatas": {
            "SESSDATA": "你的cookie",
            "bili_jct": "你的cookie",
            "DedeUserID": "你的uid"
        },
        "tasks": {}
    }]
}
```
触发器使用自定义cron `0 */10 8-23,0-1 * * * *`
![image](https://user-images.githubusercontent.com/67217225/105201427-d5bd7380-5b7b-11eb-97f8-3f5aa58a31f4.png)
