### ISSUE TITLE
关于邮箱推送的问题

### ISSUE THREAD

**Issue by GJF2015** [happy888888/BiliExp#191]
我在PUSH_MESSAGE填写了邮箱，可是却没有收到推送。
![image](https://user-images.githubusercontent.com/46737995/105789440-6998a080-5fbd-11eb-8d88-c976eccb92d5.png)

**Comment by happy888888** [comment]
两千多行消息太长了发不出去，如果只想要投票次数忽略其他一切信息可以修改`run_BiliExp.yml`文件
把
```
      env:
          ADVCONFIG: ${{ secrets.ADVCONFIG }}
          BILICONFIG: ${{ secrets.BILICONFIG }}
          PUSH_MESSAGE: ${{ secrets.PUSH_MESSAGE }}
```
修改为
```
      env:
          ADVCONFIG: ${{ secrets.ADVCONFIG }}
          BILICONFIG: ${{ secrets.BILICONFIG }}
          PUSH_MESSAGE: ${{ secrets.PUSH_MESSAGE }}
          SIMPLIFIED: 1
```

另外你的查询间隔设置得太低了，一般10-20分钟查询一次就够了，B站案件是一波一波发出的，每波的时间间隔一般都比较长，不用太频繁地查询。而且案件刚放出来投票人数很少的话程序的判断也是不准确的，投票人数更多更利于判断。
