### ISSUE TITLE
[非BUG] 关于整合一整天通知的问题

### ISSUE THREAD

**Issue by wangmanv2** [happy888888/BiliExp#229]
举个例子，比如我的账号在 Gthub Action 一天运行多次风纪委员任务，每次都推送有些不够现实（太恼人了），想知道需要如何设置 Gthub Action 才能将一整天这种多次运行的任务整合成一次推送呢？

**Comment by if1y** [comment]
Actions 每次都是一个独立的环境，所以每次运行都会产生相应的推送，其实也没啥问题

所以你可以看看**调低运行频率**（我不知道风纪是否有这种可能性），就我个人而言把运行频率调到了每天4次，还是能接受的
或者考虑在推送端处理，**对于这类消息开启勿扰（甚至不推送）**，需要了解的时候，自行查看即可

如果确实要从代码方面入手的话，感觉大概的逻辑应该是：
> 每次运行生成日志 ---- 将日志缓存到仓库 ---- 累积日志 ---- 比如每天0点，读取该文件并推送 ---- 清空日志文件内容

**Comment by wangmanv2** [comment]
我也是这样想的，但是我想询问看看有没有更优雅的方法，比如能获取到每次的执行日志，然后在设定时间的时候将他们合并并推送。

**Comment by if1y** [comment]
逻辑思路上面提供了，你可以试着改改代码（如果会的话）

**Comment by happy888888** [comment]
其实主要问题在消息储存上，因为不管是actions还是云函数都是不提供数据储存的，本项目一开始就没打算保存每次运行的数据。

目前有几种方案，我打算实现将程序设计为常驻型的，加入任务调度来分别指定每个任务包括推送的执行时间和周期，每个任务一个cron表达式。但这种方式只适合vps环境运行。

actions上可行的思路无非就是使用仓库保存日志，使用actions/cache保存日志，直接读取workflow日志
或者自己搭建一个服务器负责接受日志并保存，每天只推送一次，然后把本项目workflow地址改为你服务器的地址

**Comment by wangmanv2** [comment]
其实可以用官方提供的[Storing workflow data as artifacts](https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts)，来传递相应的数据，我还有一个疑问是怎么判断这个是一天内的东西。

**Comment by if1y** [comment]
精确度要求不高的话，就按我上面说的，例如以每日0点为时间截点，每次推送完成的时候就清空文件，那么推送的内容自然是 [-1, 0] 这两个推送之间的内容，即所需的“一天”内的日志。
如果要求高的话就要加入时间判断了，（由时间服务器提供）获得所需时间区间的内容。

**Comment by happy888888** [comment]
> 其实可以用官方提供的[Storing workflow data as artifacts](https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts)，来传递相应的数据，我还有一个疑问是怎么判断这个是一天内的东西。

怀疑官方的actions/cache就是用的这个，不用判断是不是一天内的，每次推送伴随一次清空应该可行。关键是只能同一个workflow文件访问储存

**Comment by wangmanv2** [comment]
因为不能跨 Workflow ，所以要怎么判断是否是今天的最后一次运行呢？（GMT+8）每次运行过程中校准一次时间？达到设定时间就发送，但是缺点就是每个Workflow 会推送一次。

或者联动腾讯云的 Serverless ，每运行一次传一次数据，然后定时腾讯云推送一次，然后再用一个 Actions 清空相应文件（这也太不优雅了）

或者用[note.ms](https://note.ms/)只要简单的post和get就能存储一些纯文本内容了，读取也比较简单每个地址是一个不同的文本文件，就是没加密。

**Comment by if1y** [comment]
个人觉得联动就算了吧，把事情整的更麻烦了，还不如加一条 workflow

日志存储在仓库，不用考虑跨workflow问题
只有使用 artifacts 才需要，既然不让，那么避开不就好了
然后消息推送独立用一个 workflow 设定 `cron 0 0 * * *`
不存在每个workflow 都推送一次的问题

**Comment by wangmanv2** [comment]
存储在仓库 每次存储都会有一次commit记录，如果想在本地编辑的话pull就很占用存储，而且时间线也很乱（主要是这个），并且使用仓库来存储临时文件违反了github的条款吧，很不好。

**Comment by if1y** [comment]
也有道理，那就一个 workflow + 推送时间效验

**Comment by happy888888** [comment]
```
name: 'study workflow'

on:
  schedule:
    - cron: 'cron表达式1'
    - cron: 'cron表达式2'
    - cron: 'cron表达式3'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: 任务流1步骤1
      if: github.event.schedule == 'cron表达式1'
      #这里是步骤1内容

    - name: 任务流1步骤2
      if: github.event.schedule == 'cron表达式2'
      #这里是步骤2内容

  job2:
    runs-on: ubuntu-latest
    if: github.event.schedule == 'cron表达式3'
    steps:
    - name: 任务流2步骤1
      #这里是步骤1内容

    - name: 任务流2步骤2
      #这里是步骤2内容
```

cron表达式1触发任务流1步骤1
cron表达式2触发任务流1步骤2
cron表达式3触发任务流2步骤1和步骤2(以及后面步骤)
